

CREATE TABLE musicstyle (
 styleID serial PRIMARY KEY,
 name VARCHAR(25) NOT NULL
 );
 
CREATE TABLE album (
 albumID SERIAL PRIMARY KEY,
 name VARCHAR(100) NOT NULL,
 release_date DATE NOT NULL
 );
 
CREATE TABLE artist (
 artistID SERIAL PRIMARY KEY,
 name VARCHAR(25) NOT NULL
 );

CREATE TABLE track (
 trackID SERIAL PRIMARY KEY,
 name VARCHAR(100) NOT NULL,
 duration DECIMAL (3,2) NOT NULL,
 albumID INTEGER REFERENCES album(albumID) NOT NULL
 );

CREATE TABLE artist_style (
 artist_styleID SERIAL PRIMARY KEY NOT null,
 styleID INT NOT NULL,
 artistID INT NOT NULL,
 CONSTRAINT fk_style FOREIGN KEY styleID REFERENCES musicstyle (styleID) ON DELETE CASCADE,
 CONSTRAINT fk_artist FOREIGN KEY artistID REFERENCES artist (artistiID) ON DELETE CASCADE
 );

CREATE TABLE album_artist (
 album_artistID SERIAL PRIMARY KEY,
 albumID INT NOT NULL,
 artistID INT NOT NULL,
 CONSTRAINT fk_album FOREIGN KEY albumID REFERENCES album(albumID) NO DELETE CASCADE,
 CONSTRAINT fk_artist FOREIGN KEY artistID REFERENCES artist(artistID) NO DELETE CASCADE
 ); 

CREATE TABLE collection (
 collectionID SERIAL PRIMARY KEY NOT NULL,
 name VARCHAR(100) NOT NULL,
 collection_date DATE NOT NULL,
 albumID INT NOT NULL,
 trackID INT NOT NULL.
 CONSTRAINT fk_album FOREIGN KEY albumID REFERENCES album(albumID) ON DELETE CASCADE,
 CONSTRAINT fk_track FOREIGN KEY track(trackID) ON DELETE CASCADE
 );

